import {
  ArchiveIcon,
  ArchiveXIcon,
  BoldIcon,
  BookOpenIcon,
  Code2Icon,
  CombineIcon,
  CommandIcon,
  EditIcon,
  Heading2Icon,
  Heading3Icon,
  ItalicIcon,
  LayersIcon,
  ListIcon,
  ListOrderedIcon,
  LogOutIcon,
  MoonIcon,
  PlusIcon,
  SearchIcon,
  StrikethroughIcon,
  SunIcon,
  TextIcon,
  TextQuoteIcon,
  TrashIcon,
  XIcon,
} from 'lucide-react';

export const Icons = {
  Brand: BookOpenIcon,
  Search: SearchIcon,
  Cancel: XIcon,
  Command: CommandIcon,
  Notes: LayersIcon,
  Archive: ArchiveIcon,
  UnArchive: ArchiveXIcon,
  Plus: PlusIcon,
  Delete: TrashIcon,
  Edit: EditIcon,
  Combine: CombineIcon,
  Heading2: Heading2Icon,
  Heading3: Heading3Icon,
  Bold: BoldIcon,
  Italic: ItalicIcon,
  Strike: StrikethroughIcon,
  Code: Code2Icon,
  Paragraph: TextIcon,
  BulletList: ListIcon,
  OrderedList: ListOrderedIcon,
  Blockquote: TextQuoteIcon,
  Light: SunIcon,
  Dark: MoonIcon,
  LogOut: LogOutIcon,
};
